server:
  port: 60000

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/残保金数据库?serverTimezone=GMT%2b8&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml #sql的位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制台输入查询信息
    map-underscore-to-acmel-case: true  # 开启数据库字段下划线转驼峰
  type-aliases-package: com.example.entity
