server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://124.71.219.185:3306/esfcssd?serverTimezone=GMT%2b8&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: uestc2022!
mybatis:
  mapper-locations: classpath:mapper/*.xml #sql的位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制台输入查询信息
    map-underscore-to-acmel-case: true  # 开启数据库字段下划线转驼峰
  type-aliases-package: com.example.entity
