server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/disablity_benfit?serverTimezone=GMT%2b8&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 15908136150ll
mybatis:
  mapper-locations: classpath:mapper/*.xml #sql的位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制台输入查询信息
    map-underscore-to-acmel-case: true  # 开启数据库字段下划线转驼峰
  type-aliases-package: com.example.entity
